# MAIN base
baseURL = "https://open23.de/"
languageCode = "en-us"
title = "Open23| App landing template"
theme = "open23"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Services"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "23 Max Mustermann, Grand Street, NYK."
email = "max@example.com"
phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
linkedIn = "https://www.linkedin.com/company/example"
github = "https://github.com/example"

[params]

# Header
logo = "images/logo.png"

# Footer
copyright2 = "Copyright ©  <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a> {year}"

#contact
email = "help@staticmania.com"
