# MAIN base
baseURL = "https://open23.de/"
title = "Open23| App landing template"
theme = "open23"
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
    disabled = false
    local = 'en-GB'
    direction = 'ltr'
    label = 'English'
    weight = 1
[languages.en.params]
    title = "Exmaple - Exmaple everywhere"
    copyright1 = "All right reserved"
[[languages.en.menu.main]]
    name = "Home"
    url = "#main"
    weight = 1
[[languages.en.menu.main]]
    name = "Service"
    url = "#service"
    weight = 2
[[languages.en.menu.main]]
    name = "Expertise"
    url = "#expertise"
    weight = 3
[[languages.en.menu.main]]
    name = "Team"
    url = "#team"
    weight = 4
[[languages.en.menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4
# Footer Sitemap
[[languages.en.menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[languages.en.menu.sitemap]]
    name = "Privacy policy"
    url = "/privacy"
    weight = 2
[[languages.en.menu.sitemap]]
    name = "Imprint"
    url = "/imprint"
    weight = 3
[[languages.en.menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 4

# Footer Address
[params.address]
address = "23 Max Mustermann, Grand Street, NYK."
email = "max@example.com"
phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
linkedIn = "https://www.linkedin.com/company/example"
github = "https://github.com/example"

[params]

# Header
logo = "images/logo.png"

# Footer
copyright2 = "Copyright ©  <a href=\"https://example.com/\" target=\"_blank\">Exmaple </a> {year}"

#contact
email = "help@example.com"
